#' @title Retrieve Standardized Metabolite-to-Pathway Mapping
#'
#' @description
#' Loads the final, cleaned, and aggregated metabolite-to-pathway mapping data frame
#' (\code{metab_to_pwys}) used in this package, which was generated by processing
#' metabolite data and pathway data from Human Metabolome Database(HMDB).
#'
#' This mapping is essential for scoring biochemical pathways based on individual
#' metabolite deviations in the \code{MapToPathway} function.
#'
#' This function checks for the existence of the object in the R environment
#' and assumes it was pre-loaded via \code{usethis::use_data()}.
#'
#' @return Returns the \code{metab_to_pwys} data frame to the user. Includes the following columns:
#' \itemize{
#'   \item \code{Metabolite_Name}: Standardized common name of the metabolite.
#'   \item \code{HMDB_ID}: Unique identifier of the metabolite
#'   \item \code{Pathway_Name}: Standardized name of the biochemical pathway the metabolite belongs to.
#' }
#'
#' @examples
#' # Example 1: load the reference dataset
#' map_df <- GetPathwayMap()
#' head(map_df)
#'
#' @references
#' \strong{HMDB Metabolite Reference Data}:
#' Wishart, D. S., et al. (2022). HMDB 5.0: The Human Metabolome Database for 2022.
#' Nucleic Acids Research, 50(D1), D1-D10. Retrieved from \href{https://hmdb.ca/}{HMDB}.
#'
#' \strong{Debugging Assistance:}
#' Google. (2025). Gemini (v 2.0 Flash) [Large language model]. \href{https://gemini.google.com}{Gemini}
#'
#' @importFrom utils data
#' @export
GetPathwayMap <- function() {

  data_object_name <- "metab_to_pwys"
  map_df <- NULL

  # Check if the object is already loaded in the environment.
  if (exists(data_object_name, envir = .GlobalEnv)) {
    map_df <- get(data_object_name, envir = .GlobalEnv)

  } else {
    # Attempt to load the data
    load_success <- tryCatch({
      data(data_object_name, package = "MetaNetis", envir = environment())
      TRUE
    }, error = function(e) {
      stop("Pathway mapping data missing, please reinstall the package or Retry.")
    })

    if (load_success) {
      map_df <- get(data_object_name)
    }
  }

  return(map_df)
}

# [END]
