#' @title Retrieve Standardized Metabolite-to-Pathway Mapping
#'
#' @description
#' Loads the final, cleaned, and aggregated metabolite-to-pathway mapping data frame
#' (\code{metab_to_pwys}) used in this package, which was generated by processing
#' metabolite data and pathway data from Human Metabolome Database(HMDB).
#'
#' This mapping is essential for scoring biochemical pathways based on individual
#' metabolite deviations in the \code{MapToPathway} function.
#'
#' This function checks for the existence of the object in the R environment
#' and assumes it was pre-loaded via \code{usethis::use_data()}.
#'
#' @return Returns the \code{metab_to_pwys} data frame to the user. Includes the
#' following columns:
#' \itemize{
#'   \item \code{Metabolite_Name}: Standardized common name of the metabolite.
#'   \item \code{HMDB_ID}: Unique identifier of the metabolite
#'   \item \code{Pathway_Name}: Standardized name of the biochemical pathway
#'    the metabolite belongs to.
#' }
#'
#' @examples
#' # Example 1: load the reference dataset
#' map_df <- MetaNetis::GetPathwayMap()
#' head(map_df)
#'
#' @author Yunze Du, \email{yunze.du@mail.utoronto.ca}
#'
#' @references
#' \strong{HMDB Metabolite Reference Data}:
#' Wishart, D. S., et al. (2022). HMDB 5.0: The Human Metabolome Database for 2022.
#' Nucleic Acids Research, 50(D1), D1-D10. Retrieved from \href{https://hmdb.ca/}{HMDB}.
#'
#' \strong{Debugging Assistance:}
#' Google. (2025). Gemini (v 2.0 Flash) [Large language model].
#'  \href{https://gemini.google.com}{Gemini}
#'
#' @importFrom utils data
#' @export
GetPathwayMap <- function() {

  # Initialize output
  map_df <- NULL

  # Path to default dataset in package
  default_file <- system.file("data", "metab_to_pwys.rda",
                              package = "MetaNetis")

  # Attempt to load default dataset
  load_success <- tryCatch({
    map_df <- MetaNetis::metab_to_pwys
    TRUE
  }, error = function(e) {
    FALSE
  })

  if (!load_success) {
    stop(
      "Failed to load default 'metab_to_pwys'. Please reinstall the MetaNetis package.")
  } else {

  }

  return(map_df)
}

# [END]
