#' @title Retrieve Standardized Human Metabolite Reference Ranges
#'
#' @description
#' Loads the final, cleaned, and aggregated human reference range data frame
#' (`reference_ranges_df`) used in this package, which was generated by processing
#' the Human Metabolome Database Metabolite(HMBD) Reference Data XML dataset
#' from \url{https://hmdb.ca/downloads}.
#'
#' The original HMDB data was extensively cleaned to produce a robust dataset
#' suitable for comparing user metabolomic profiles against healthy controls.
#' The key cleaning and standardization steps performed include:
#' \itemize{
#'   \item \strong{Filtering:} Removed all non-specific entries such as "Unknown,"
#'         "Not Specified," and ranges containing only one reference (e.g., mean only).
#'   \item \strong{Merging & Ranging:} Metabolite entries were grouped by Name,
#'         Biofluid, and Subject Age Description. The final \code{Min_Concentration}
#'         and \code{Max_Concentration} ranges were determined by taking the
#'         minimum of all minimums and the maximum of all maximums for the
#'         metabolite group with same Sample_Type and Subject_Age_Description.
#'   \item \strong{Age Standardization:} Age ranges were parsed from free-text
#'         descriptions and converted into standardized \code{Min_Age(year)} and
#'         \code{Max_Age(year)} columns, handling units (days, months, years)
#'         and symbols (>, <, single values).
#' }
#'
#' It first checks if an alternative reference dataset (`alt_ref_ranges.rda`) exists
#' in the package's data directory. If it does, that dataset is loaded and returned.
#' Otherwise, the default `reference_ranges_df` included in the package is returned.
#'
#' @return Returns an the 'ref_df' data frame to the user. Includes the
#' following columns:
#' \itemize{
#'   \item \code{HMDB_ID}: Unique identifier of the metabolite.
#'   \item \code{Metabolite_Name}: Common name of the metabolite.
#'   \item \code{Sample_Type}: Standardized biological fluid type
#'   (e.g., Blood/Serum/Plasma, CSF, Urine).
#'   \item \code{Subject_Age_Description}: The original age group description
#'   from the HMDB dataset.
#'   \item \code{Min_Age(year)}: Minimum age (in years) for the applicable
#'   age group.
#'   \item \code{Max_Age(year)}: Maximum age (in years) for the applicable
#'   age group (\code{Inf} for general adult groups).
#'   \item \code{Min_Concentration(Healthy)}: Minimum concentration observed
#'   in healthy individuals within the age group.
#'   \item \code{Mean_Concentration(Healthy)}: Aggregated average concentration
#'   in healthy individuals within the age group.
#'   \item \code{Max_Concentration(Healthy)}: Maximum concentration observed
#'   in healthy individuals within the age group.
#'   \item \code{Unit}: The unit of measurement for concentration
#'   (e.g., uM, umol/mmol creatinine).
#' }
#'
#' @examples
#' # Example 1: load the reference dataset
#' ref_df <- GetRefRanges()
#' head(ref_df)
#'
#' @author Yunze Du, \email{yunze.du@mail.utoronto.ca}
#'
#' @references
#' \strong{HMDB Metabolite Reference Data}:
#' Wishart, D. S., et al. (2022). HMDB 5.0: The Human Metabolome Database for 2022.
#' Nucleic Acids Research, 50(D1), D1-D10. Retrieved from
#' \href{https://hmdb.ca/}{HMDB}.
#'
#' \strong{Debugging Assistance:}
#' Google. (2025). Gemini (v 2.0 Flash) [Large language model].
#' \href{https://gemini.google.com}{Gemini}
#'
#' @importFrom utils data
#' @export
GetRefRanges <- function() {

  # Initialize output
  ref_df <- NULL

  # Path to optional alternative file in the package data directory
  alt_file <- file.path(Sys.getenv("HOME"), ".MetaNetis", "alt_ref_ranges.rds")

  # Attempt to load alternative dataset if it exists
  if (file.exists(alt_file)) {
    # Load alternative dataset directly
    load_success <- tryCatch({
      ref_df <- readRDS(alt_file)
      TRUE
    }, error = function(e) {
      FALSE
    })

    if (!load_success) {
      stop("Failed to load 'alt_ref_ranges.rda'. Please check the file.")
    } else {

    }

  } else {
    # Load default dataset from package
    load_success <- tryCatch({
      ref_df <- MetaNetis::reference_ranges_df
      TRUE
    }, error = function(e) {
      FALSE
    })

    if (!load_success) {
      stop(
        "Failed to load default 'reference_ranges_df'.
        Please reinstall the MetaNetis package.")
    } else {

    }
  }

  return(ref_df)
}

# [END]
