#' @title Retrieve Standardized Human Metabolite Reference Ranges
#'
#' @description
#' Loads the final, cleaned, and aggregated human reference range data frame
#' (`reference_ranges_df`) used in this package, which was generated by processing
#' the Human Metabolome Database Metabolite(HMBD) Reference Data XML dataset
#' from \url{https://hmdb.ca/downloads}.
#'
#' The original HMDB data was extensively cleaned to produce a robust dataset
#' suitable for comparing user metabolomic profiles against healthy controls.
#' The key cleaning and standardization steps performed include:
#' \itemize{
#'   \item \strong{Filtering:} Removed all non-specific entries such as "Unknown,"
#'         "Not Specified," and ranges containing only one reference (e.g., mean only).
#'   \item \strong{Merging & Ranging:} Metabolite entries were grouped by Name,
#'         Biofluid, and Subject Age Description. The final \code{Min_Concentration}
#'         and \code{Max_Concentration} ranges were determined by taking the
#'         minimum of all minimums and the maximum of all maximums for the
#'         metabolite group with same Sample_Type and Subject_Age_Description.
#'   \item \strong{Age Standardization:} Age ranges were parsed from free-text
#'         descriptions and converted into standardized \code{Min_Age(year)} and
#'         \code{Max_Age(year)} columns, handling units (days, months, years)
#'         and symbols (>, <, single values).
#' }
#'
#' This function first checks for the existence of the object in the global environment
#' and loads it from the package data if missing.
#'
#' @return Returns an the 'reference_range_df' data frame to the user. Includes the following columns:
#' \itemize{
#'   \item \code{HMDB_ID}: Unique identifier of the metabolite.
#'   \item \code{Metabolite_Name}: Common name of the metabolite.
#'   \item \code{Sample_Type}: Standardized biological fluid type (e.g., Blood/Serum/Plasma, CSF, Urine).
#'   \item \code{Subject_Age_Description}: The original age group description from the HMDB dataset.
#'   \item \code{Min_Age(year)}: Minimum age (in years) for the applicable age group.
#'   \item \code{Max_Age(year)}: Maximum age (in years) for the applicable age group (\code{Inf} for general adult groups).
#'   \item \code{Min_Concentration(Healthy)}: Minimum concentration observed in healthy individuals within the age group.
#'   \item \code{Mean_Concentration(Healthy)}: Aggregated average concentration in healthy individuals within the age group.
#'   \item \code{Max_Concentration(Healthy)}: Maximum concentration observed in healthy individuals within the age group.
#'   \item \code{Unit}: The unit of measurement for concentration (e.g., uM, umol/mmol creatinine).
#' }
#'
#' @examples
#' # Example 1: load the reference dataset
#' ref_df <- GetRefRanges()
#' head(ref_df)
#'
#' @references
#' \strong{HMDB Metabolite Reference Data}:
#' Wishart, D. S., et al. (2022). HMDB 5.0: The Human Metabolome Database for 2022.
#' Nucleic Acids Research, 50(D1), D1-D10. Retrieved from \href{https://hmdb.ca/}{HMDB}.
#'
#' \strong{Debugging Assistance:}
#' Google. (2025). Gemini (v 2.0 Flash) [Large language model]. \href{https://gemini.google.com}{Gemini}
#'
#' @export
GetRefRanges <- function() {

  data_object_name <- "reference_ranges_df"
  ref_df <- NULL

  # Check if the object is already loaded in the environment.
  if (exists(data_object_name, envir = .GlobalEnv)) {
    ref_df <- get(data_object_name, envir = .GlobalEnv)

  } else {
    # Attempt to load the data
    load_success <- tryCatch({
      data(data_object_name)
      TRUE
    }, error = function(e) {
      stop("Reference data missing, please reinstall the package or load altertative reference range with SetAltBaseline().")
    })

    if (load_success) {
      ref_df <- get(data_object_name)
    }
  }

  return(ref_df)
}

# [END]
