#' @title Set an Alternative Reference Range Baseline
#'
#' @description
#' Loads a user-provided data source (either a file path to a CSV or a data frame object)
#' and assigns it to the name \code{reference_ranges_df} in the global environment,
#' overriding the default packaged data.
#'
#' This function is useful for researchers who wish to use institution-specific,
#' population-specific, or more up-to-date reference ranges than those bundled
#' with the package.
#'
#' @param data_source Either a character string specifying the file path to a CSV file
#'   or a data frame object containing the alternative reference range data. If left
#'   empty, then the default reference_ranges_df from Human Metabolome Database(HMDB)
#'   will be loaded.
#'
#' @details
#' The replacement data frame MUST have the following column names (matching those
#' generated by the data cleaning pipeline):
#' \itemize{
#'   \item \code{HMDB_ID}: Unique identifier of the metabolite.
#'   \item \code{Metabolite_Name}: Common name of the metabolite.
#'   \item \code{Sample_Type}: Standardized biological fluid type (e.g., Blood/Serum/Plasma, CSF, Urine).
#'   \item \code{Subject_Age_Description}: The original age group description from the HMDB dataset.
#'   \item \code{Min_Age(year)}: Minimum age (in years) for the applicable age group.
#'   \item \code{Max_Age(year)}: Maximum age (in years) for the applicable age group (\code{Inf} for general adult groups).
#'   \item \code{Min_Concentration(Healthy)}: Minimum concentration observed in healthy individuals within the age group.
#'   \item \code{Mean_Concentration(Healthy)}: Aggregated average concentration in healthy individuals within the age group.
#'   \item \code{Max_Concentration(Healthy)}: Maximum concentration observed in healthy individuals within the age group.
#'   \item \code{Unit}: The unit of measurement for concentration (e.g., uM, umol/mmol creatinine).
#' }
#'
#'@examples
#' # Example 1:
#' ref_df <- data.frame(
#'   HMDB_ID = c("HMDB0000190", "HMDB0000064", "HMDB0000001", "HMDB0001918"),
#'   Metabolite_Name = c("L-Tryptophan", "Creatinine", "1-Methylhistidine", "Glucose"),
#'   Sample_Type = c("Blood/Serum/Plasma", "Urine", "CSF", "Blood/Serum/Plasma"),
#'   Subject_Age_Description = c("Adult (>18 years old)", "Newborn (0-30 days old)", "Adolescent (13-18 years old)", "Children (1-13 years old)"),
#'
#'   `Min_Age(year)` = c(18.0, 0.0, 13.0, 1.0),
#'   `Max_Age(year)` = c(Inf, 0.082, 18.0, 13.0),
#'   `Min_Concentration(Healthy)` = c(50.0, 0.15, 0.012, 3500.0),
#'   `Mean_Concentration(Healthy)` = c(75.5, 0.25, 0.021, 5200.0),
#'   `Max_Concentration(Healthy)` = c(100.0, 0.50, 0.030, 8000.0),
#'   Unit = c("uM", "umol/mmol creatinine", "uM", "uM"),
#'   stringsAsFactors = FALSE,
#'   check.names = FALSE
#' )
#'
#' SetAltBaseline(ref_df)
#' GetRefRanges()
#' SetAltBaseline()
#'
#' @references
#' \strong{HMDB Metabolite Reference Data}:
#' Wishart, D. S., et al. (2022). HMDB 5.0: The Human Metabolome Database for 2022.
#' Nucleic Acids Research, 50(D1), D1-D10. Retrieved from \href{https://hmdb.ca/}{HMDB}.
#'
#' \strong{Debugging Assistance:}
#' Google. (2025). Gemini (v 2.0 Flash) [Large language model]. \href{https://gemini.google.com}{Gemini}
#'
#' @export
SetAltBaseline <- function(data_source = NULL) {

  # If parameter is NULL, load original data frame
  if (is.null(data_source)) {
    message("Provided data is empty. Loading original package reference data...")
    data("reference_ranges_df", package = "MetaNetis")
    assign("reference_ranges_df", get("reference_ranges_df"), envir = .GlobalEnv)
    return(invisible(NULL))
  }

  # If Not empty
  new_baseline_df <- NULL
  required_cols <- c(
    "HMDB_ID", "Metabolite_Name", "Sample_Type", "Subject_Age_Description",
    "Min_Age(year)", "Max_Age(year)", "Min_Concentration(Healthy)",
    "Mean_Concentration(Healthy)", "Max_Concentration(Healthy)", "Unit"
  )

  # Case 1: Input is a csv file path
  if (is.character(data_source)) {
    csv_path <- data_source
    if (!file.exists(csv_path)) {
      stop(paste("Error: File not found at path:", csv_path))
    }

    new_baseline_df <- tryCatch({
      read.csv(csv_path, stringsAsFactors = FALSE)
    }, error = function(e) {
      stop(paste("Failed to read CSV file:", e$message))
    })

    message(paste("Successfully loaded alternative reference ranges from file:", csv_path))

  } else if (is.data.frame(data_source)) {
    # Case 2: Input is a data frame
    new_baseline_df <- data_source
    message("Successfully loaded alternative reference ranges from provided data frame.")

  } else {
    # Case 3: Invalid input type
    stop("Error: 'data_source' must be a valid csv file path (character) or a data frame (data.frame).")
  }

  # Sanity check: if the new data frame is empty
  if (is.null(new_baseline_df) || nrow(new_baseline_df) == 0) {
    stop("The provided data source resulted in an empty or invalid data frame.")
  }

  # Sanity check: Do the column names matches
  if (!all(required_cols %in% names(new_baseline_df))) {
    missing_cols <- setdiff(required_cols, names(new_baseline_df))
    stop(paste0(
      "Error: The alternative baseline data frame is missing required columns. Missing: ",
      paste(missing_cols, collapse = ", ")
    ))
  }

  # In case the order is messed up
  new_baseline_df <- new_baseline_df[, required_cols]

  # Assign the loaded data frame to the target name in the environment.
  assign("reference_ranges_df", new_baseline_df, envir = .GlobalEnv)
  message("The default package reference data has been updated.")

}

# [END]
